import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import ci from "miniprogram-ci";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packageJsonPath = path.join(projectRoot, "package.json");
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
const dependencies = packageJson.dependencies ?? {};

if (Object.keys(dependencies).length === 0) {
  const outputDir = path.join(projectRoot, "miniprogram_npm");
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(
    path.join(outputDir, ".gitkeep"),
    "This directory is generated by WeChat npm build and ignored by git.\n",
  );
  console.log("No Mini Program runtime dependencies to pack yet; prepared miniprogram_npm.");
} else {
  await ci.packNpmManually({
    packageJsonPath,
    miniprogramNpmDistDir: projectRoot,
  });
}
